### PR TITLE
Initial setup

### PR DESCRIPTION
**Pull request by Mrtenz**
This is the initial set up of the repository, based on `metamask-module-template`. This adds the following:

- A basic React website.
   - Built with Webpack.
   - Routing is set up with `react-router-dom`, using the hash router (for GitHub Pages compatibility).
   - A basic Redux store with `redux-saga` is set up.
- Basic component tests with Jest and `@testing-library/react`.
- Deployment to GitHub Pages.

### CODE REVIEW

**Comment by Mrtenz** [comment]
@SocketSecurity ignore @lavamoat/aa@3.1.2
@SocketSecurity ignore @lavamoat/allow-scripts@2.3.1
@SocketSecurity ignore @swc/core@1.3.56
@SocketSecurity ignore core-js-pure@3.30.2
@SocketSecurity ignore @lavamoat/preinstall-always-fail@1.0.0
@SocketSecurity ignore simple-git-hooks@2.8.1
@SocketSecurity ignore jest@28.1.3
@SocketSecurity ignore jest-cli@28.1.3
@SocketSecurity ignore @babel/parser@7.16.4
@SocketSecurity ignore @istanbuljs/load-nyc-config@1.1.0
@SocketSecurity ignore @jest/create-cache-key-function@27.5.1
@SocketSecurity ignore @metamask/auto-changelog@3.1.0
@SocketSecurity ignore @nodelib/fs.stat@2.0.5
@SocketSecurity ignore @npmcli/fs@2.1.2
@SocketSecurity ignore @npmcli/move-file@2.0.1
@SocketSecurity ignore @npmcli/node-gyp@3.0.0
@SocketSecurity ignore @swc/jest@0.2.26
@SocketSecurity ignore @vue/compiler-sfc@3.2.47
@SocketSecurity ignore acorn@8.8.2
@SocketSecurity ignore ajv@6.12.6
@SocketSecurity ignore argparse@1.0.10
@SocketSecurity ignore babel-plugin-istanbul@6.1.1
@SocketSecurity ignore bplist-parser@0.2.0
@SocketSecurity ignore chokidar@3.5.3
@SocketSecurity ignore chownr@2.0.0
@SocketSecurity ignore commander@10.0.1
@SocketSecurity ignore commander@2.20.3
@SocketSecurity ignore commander@9.5.0
@SocketSecurity ignore convert-source-map@1.9.0
@SocketSecurity ignore cosmiconfig@7.1.0
@SocketSecurity ignore create-require@1.1.1
@SocketSecurity ignore cross-spawn@7.0.3
@SocketSecurity ignore debug@2.6.9
@SocketSecurity ignore debug@3.2.7
@SocketSecurity ignore debug@4.3.4
@SocketSecurity ignore default-browser-id@3.0.0
@SocketSecurity ignore depcheck@1.4.3
@SocketSecurity ignore destroy@1.2.0
@SocketSecurity ignore envinfo@7.8.1
@SocketSecurity ignore escalade@3.1.1
@SocketSecurity ignore eslint-module-utils@2.8.0
@SocketSecurity ignore eslint-plugin-import@2.27.5
@SocketSecurity ignore eslint-plugin-jest@27.2.1
@SocketSecurity ignore eslint-plugin-node@11.1.0
@SocketSecurity ignore eslint-plugin-react@7.32.2
@SocketSecurity ignore esprima@4.0.1
@SocketSecurity ignore etag@1.8.1
@SocketSecurity ignore express@4.18.2
@SocketSecurity ignore find-root@1.1.0
@SocketSecurity ignore form-data@4.0.0

**Comment by Mrtenz** [comment]
@SocketSecurity ignore fs-minipass@2.1.0
@SocketSecurity ignore fs.realpath@1.0.0
@SocketSecurity ignore get-package-type@0.1.0
@SocketSecurity ignore glob@7.2.3
@SocketSecurity ignore glob@8.1.0
@SocketSecurity ignore html-minifier-terser@6.1.0
@SocketSecurity ignore html-webpack-plugin@5.5.1
@SocketSecurity ignore infer-owner@1.0.4
@SocketSecurity ignore is-docker@2.2.1
@SocketSecurity ignore is-docker@3.0.0
@SocketSecurity ignore is-wsl@2.2.0
@SocketSecurity ignore isexe@2.0.0
@SocketSecurity ignore istanbul-lib-report@3.0.0
@SocketSecurity ignore istanbul-lib-source-maps@4.0.1
@SocketSecurity ignore jest-haste-map@28.1.3
@SocketSecurity ignore jest-it-up@2.2.0
@SocketSecurity ignore js-yaml@3.14.1
@SocketSecurity ignore jsdom@20.0.3
@SocketSecurity ignore json5@1.0.2
@SocketSecurity ignore json5@2.2.3
@SocketSecurity ignore jsonfile@6.1.0
@SocketSecurity ignore launch-editor@2.6.0
@SocketSecurity ignore locate-path@5.0.0
@SocketSecurity ignore locate-path@6.0.0
@SocketSecurity ignore loose-envify@1.4.0
@SocketSecurity ignore make-dir@3.1.0
@SocketSecurity ignore mime@1.6.0
@SocketSecurity ignore mkdirp@1.0.4
@SocketSecurity ignore node-gyp@9.3.1
@SocketSecurity ignore open@8.4.2
@SocketSecurity ignore path-type@4.0.0
@SocketSecurity ignore postcss@8.4.23
@SocketSecurity ignore prettier@2.8.8
@SocketSecurity ignore read-cmd-shim@4.0.0
@SocketSecurity ignore readdirp@3.6.0
@SocketSecurity ignore require-directory@2.1.1
@SocketSecurity ignore resolve@2.0.0-next.4
@SocketSecurity ignore resolve-from@4.0.0
@SocketSecurity ignore resolve-from@5.0.0
@SocketSecurity ignore rimraf@3.0.2
@SocketSecurity ignore sass@1.62.1
@SocketSecurity ignore send@0.18.0
@SocketSecurity ignore sockjs@0.3.24
@SocketSecurity ignore source-map@0.7.4
@SocketSecurity ignore source-map@0.5.7
@SocketSecurity ignore source-map-support@0.5.13
@SocketSecurity ignore source-map-support@0.5.21
@SocketSecurity ignore tar@6.1.14
@SocketSecurity ignore ts-node@10.9.1
@SocketSecurity ignore tsconfig-paths@3.14.2

**Comment by Mrtenz** [comment]
@SocketSecurity ignore typescript@4.8.4
@SocketSecurity ignore v8-compile-cache-lib@3.0.1
@SocketSecurity ignore walker@1.0.8
@SocketSecurity ignore webpack-cli@5.1.0
@SocketSecurity ignore webpack-dev-middleware@5.3.3
@SocketSecurity ignore write-file-atomic@4.0.2
@SocketSecurity ignore write-file-atomic@5.0.1
@SocketSecurity ignore y18n@5.0.8
@SocketSecurity ignore yargs@16.2.0
@SocketSecurity ignore yargs@17.7.2
@SocketSecurity ignore yargs-parser@20.2.9
@SocketSecurity ignore yargs-parser@21.1.1
@SocketSecurity ignore fork-ts-checker-webpack-plugin@8.0.0
@SocketSecurity ignore memfs@3.5.1
@SocketSecurity ignore cacache@16.1.3
@SocketSecurity ignore bin-links@4.0.1
@SocketSecurity ignore cmd-shim@6.0.1
@SocketSecurity ignore read-package-json-fast@3.0.2
@SocketSecurity ignore faye-websocket@0.11.4
@SocketSecurity ignore http-proxy-agent@5.0.0
@SocketSecurity ignore https-proxy-agent@5.0.1
@SocketSecurity ignore socks-proxy-agent@7.0.0
@SocketSecurity ignore spdy@4.0.2
@SocketSecurity ignore ws@8.13.0
@SocketSecurity ignore @reduxjs/toolkit@1.9.5
@SocketSecurity ignore @remix-run/router@1.6.1
@SocketSecurity ignore domutils@2.8.0
@SocketSecurity ignore make-fetch-happen@10.2.1
@SocketSecurity ignore micro-ftch@0.3.1
@SocketSecurity ignore minipass-fetch@2.1.2
@SocketSecurity ignore node-abort-controller@3.1.1
@SocketSecurity ignore webpack-dev-server@4.15.0
@SocketSecurity ignore agentkeepalive@4.3.0
@SocketSecurity ignore follow-redirects@1.15.2
@SocketSecurity ignore http-proxy@1.18.1
@SocketSecurity ignore default-gateway@6.0.3
@SocketSecurity ignore fb-watchman@2.0.2
@SocketSecurity ignore socks@2.7.1
@SocketSecurity ignore body-parser@1.20.1
@SocketSecurity ignore raw-body@2.5.1
@SocketSecurity ignore websocket-driver@0.7.4
@SocketSecurity ignore methods@1.1.2
@SocketSecurity ignore bonjour-service@1.1.1
@SocketSecurity ignore http-proxy-middleware@2.0.6
@SocketSecurity ignore @npmcli/promise-spawn@6.0.2
@SocketSecurity ignore execa@5.1.1
@SocketSecurity ignore @chainsafe/ssz@0.11.1
@SocketSecurity ignore concat-map@0.0.1
@SocketSecurity ignore minipass-collect@1.0.2
@SocketSecurity ignore minipass-pipeline@1.2.4

**Comment by Mrtenz** [comment]
@SocketSecurity ignore-all

**Review by FrederikBolding — APPROVED** [review]

**Pull request merged**
